spring.application.name=Track-Activity

server.port=8081

# AWS region. Defaults to Mumbai if AWS_REGION is not supplied.
aws.region=${AWS_REGION:ap-south-1}

# DynamoDB table name.
aws.dynamodb.plan-table-name=${DYNAMODB_TABLE_NAME:Plan}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:activity}
aws.dynamodb.user-table-name=${aws.dynamodb.user-table-nam:Users}
aws.dynamodb.activity-table-name=${DYNAMODB_TABLE_NAME:DailyActivity}

# Swagger Details (Optional if you not add still its work
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs